#docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
version: '3.8'
services:
  uptime:
    image: louislam/uptime-kuma:1.18.5-alpine
    container_name: uptime_kuma
    volumes:
      - ./uptime-kuma:/app/data
    #ports:
    # - 8080:3001
    env_file:
      - file-${ENV}.env

    networks:
      - proxy_nt

    labels:
      # enable traefik
      - "traefik.enable=true"
      # router
      - "traefik.http.routers.${ROUTEUR_NAME}.rule=Host(`${HOST_NAME}`)"
      - "traefik.http.routers.${ROUTEUR_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${ROUTEUR_NAME}.service=${SERVICE_NAME}"
      # certificate SSL HTTPS
      - traefik.http.routers.${ROUTEUR_NAME}.tls=true
      - traefik.http.routers.${ROUTEUR_NAME}.tls.certresolver=lets-encrypt
      # service
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${CONTAINER_PORT}
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.scheme=http
        
    

networks:
  proxy_nt:
    external: true















