#docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
version: '3.8'
services:
  uptime:
    image: louislam/uptime-kuma:1.18.5-alpine
    container_name: uptime_kuma
    volumes:
      - ./uptime-kuma:/app/data
    #ports:
    # - 8080:3001
    env_file:
      - file-${ENV}.env

    networks:
      - proxy_nt
        
    

networks:
  proxy_nt:
    external: true















