#docker run -d --name=grafana -p 3000:3000 grafana/grafana
#docker pull grafana/grafana:9.2.6-ubuntu

version: '3.8'
services:
  grafana:
    image: grafana/grafana:9.2.6-ubuntu
    container_name: grafana_ct
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
     # - ./uptime-kuma:/app/data
    #for the moment eliminated to be checked
    #ports:
    # - 8080:3000
    environment:
      # - VIRTUAL_HOST=grafana.city.local
      - VIRTUAL_HOST=grafana.devops-hunter.com
      - LETSENCRYPT_HOST=grafana.devops-hunter.com
      - LETSENCRYPT_EMAIL=chatti.khalil31@gmail.com
      - VIRTUAL_PORT=3000
      - TZ=UTC 
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ACCOUNT_USERNAME:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ACCOUNT_PASS:-admin}
    #PASSWORD: "${PASSWORD:-admin}" Another method to declare variables 
      
    networks:
      - proxy_nt
        
volumes:
  grafana_data:
    name: grafana_data
    driver: local
networks:
  proxy_nt:
    external: true
