version: '3.8'
services:
  prometheus-blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox_ct
    volumes:
      - ./config.yml:/etc/blackbox_exporter/config.yml
    env_file:
      - file${ENV}.env

    networks:
      - proxy_nt
    restart: unless-stopped
        
    
networks:
  proxy_nt:
    external: true
 