apiVersion: 1

deleteDatasources:
  - name: Prometheus-cityhunter
    orgId: 1

datasources:
- name: Prometheus-cityhunter
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  version: 1
  editable: false