version: '3.8'
services:
  city-site-apache2:
    image: cityhunterxx/cityhuntersite:apache2
    container_name: city
    environment:
      - VIRTUAL_HOST=city.local
      - VIRTUAL_PORT=80
      - TZ=UTC 
    networks:
      - proxy_nt
networks:
  proxy_nt:
    external: true