version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_ct
    #ports:
    #- 9090:9090
    command:
    - --web.enable-lifecycle
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    environment:
      # - VIRTUAL_HOST=prometheus.city.local
      - VIRTUAL_HOST=prometheus.devops-hunter.com
      - LETSENCRYPT_HOST=prometheus.devops-hunter.com
      - LETSENCRYPT_EMAIL=chatti.khalil31@gmail.com
      - VIRTUAL_PORT=9090
      - TZ=UTC 
    networks:
      - proxy_nt
    
        
networks:
  proxy_nt:
    external: true