version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    #ports:
    #- 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    environment:
      - VIRTUAL_HOST=prometheus.city.local
      - VIRTUAL_PORT=9090
      - TZ=UTC 
    networks:
      - proxy_nt
        
    
networks:
  proxy_nt:
    external: true