version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_ct
    ports:
    - 9090:9090
    command:
    - --web.enable-lifecycle
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    env_file:
      - file${ENV}.env

    networks:
      - proxy_nt
    
        
networks:
  proxy_nt:
    external: true