version: '3.8'
services:
  city-site-python:
    build: .
    image: ${BASE_IMAGE}:python
    container_name: city-compose0
    ports:
      - 8080:80
  city-site-nginx:
    image: ${BASE_IMAGE}:nginx
    container_name: city-compose1
    ports:
      - 8082:80
    environment:
      - TZ=UTC 
  city-site-apache2:
    image: ${BASE_IMAGE}:apache2
    container_name: city-compose2
    ports:
      - 8084:80
    environment:
      - TZ=UTC 
  