#docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
#docker volume create portainer_data

version: '3.8'
services:
  portainer:
    image: ${PORTAINER_IMAGE}
    container_name: portainer-ct
    #ports:
      #- 9443:9443
    restart: always 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      #./xxxxxx will create a file that'll store the C data on it
    networks:
      - nt_portainer
      - proxy_nt
      #- nt_vm
    env_file:
      - file.env

volumes:
  portainer_data:
    name: portainer_data
    driver: local

networks:
  nt_portainer:
    name: nt_portainer

  proxy_nt:
    external: true

    
