name: portainer
services:
  portainer:
    container_name: portainer-ct
    image: portainer/portainer-ce:latest
    networks:
      default: null
    ports:
    - mode: ingress
      target: 9443
      published: "9443"
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      bind:
        create_host_path: true
    - type: volume
      source: portainer_data
      target: /data
      volume: {}
networks:
  default:
    name: portainer_default
volumes:
  portainer_data:
    name: portainer_portainer_data
    driver: local