version: "3.8"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.5.3
    container_name: heimdall_ct
    environment:
      - PUID=1000
      - PGID=1000
      # - VIRTUAL_HOST=heimdall.city.local 
      - VIRTUAL_HOST=heimdall.devops-hunter.com
      - LETSENCRYPT_HOST=heimdall.devops-hunter.com
      - LETSENCRYPT_EMAIL=chatti.khalil31@gmail.com
      - VIRTUAL_PORT=80
      #- VIRTUAL_PROTO=HTTPS
      - TZ=UTC 
    volumes:
      - ./appdata_config:/config
    #ports:
     # - 80:80
     # - 443:443
    restart: unless-stopped
    networks:
      - proxy_nt
    
networks:
  proxy_nt:
    external: true