version: "3.8"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.5.3
    container_name: heimdall_ct
    env_file:
      - file-${ENV}.env

    volumes:
      - ./appdata_config:/config
    #ports:
     # - 80:80
     # - 443:443
    restart: unless-stopped
    networks:
      - proxy_nt
    
networks:
  proxy_nt:
    external: true